services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=image'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
volumes:
  postgres_data:
